export const BUSINESS_INFO = {
  name: 'PANWAR ENTERPRISES',
  tagline: 'Industrial Scrap Buying & Collection',
  phone: '9813155887',
  whatsapp: '9813155887',
  whatsappFormatted: '+919813155887',
  email: 'bhimsingh@9812gmail.com',
  address: {
    village: 'Village Tankri',
    tehsil: 'Tehsil Bawal',
    district: 'District Rewari',
    state: 'Haryana',
    country: 'India',
    full: 'Village Tankri, Tehsil Bawal, District Rewari, Haryana, India',
    short: 'Tankri, Bawal, Rewari, Haryana',
  },
  hours: '24×7, All Days',
  experienceYears: '35+',
  usps: [
    'Best price in the market',
    '35+ years of experience',
    'Fast scrap pickup',
    'Easy enquiry process',
    'Industrial/company scrap collection',
    'Professional and reliable service',
  ],
  serviceAreas: [
    { name: 'Gurugram', desc: 'Udyog Vihar, Manesar corridor, DLF Industrial, Behrampur' },
    { name: 'Manesar', desc: 'IMT Manesar Sector 1-8, Roz-Ka-Meo, Maruti & ancillary zone' },
    { name: 'Bawal', desc: 'HSIIDC Industrial Estate Sector 1-5, NH-48 corridor' },
    { name: 'Neemrana', desc: 'RIICO Industrial Area, Japanese Zone, EPIP zone' },
    { name: 'Rewari', desc: 'Dharuhera, Rewari City, Industrial Area Phase 1 & 2' },
    { name: 'Nearby Industrial Areas', desc: 'Dharuhera, Khushkhera, Tapukara, Bilaspur, Pataudi' },
  ],
};

export const SCRAP_CATEGORIES = [
  {
    id: 'iron-scrap',
    name: 'Iron Scrap',
    tag: 'Ferrous',
    description: 'Heavy melting iron, cast iron dies, structural girders, industrial beams, lathe turnings, machine beds.',
    icon: 'Hammer',
    typicalSources: 'Fabrication yards, machine shops, casting units',
  },
  {
    id: 'steel-scrap',
    name: 'Steel Scrap',
    tag: 'Alloy & Ferrous',
    description: 'Stainless steel (SS 304, 316), mild steel (MS) plate cuts, CRC/HRC sheets, structural channels, pipes.',
    icon: 'Layers',
    typicalSources: 'Automotive pressing, pipe manufacturers, fabrication units',
  },
  {
    id: 'aluminium-scrap',
    name: 'Aluminium Scrap',
    tag: 'Non-Ferrous',
    description: 'Extrusion 6063 off-cuts, aluminium engine blocks, tense, casting scrap, UBC, sheet cuts, wire scrap.',
    icon: 'Shield',
    typicalSources: 'Extrusion plants, auto component foundries, architectural facade makers',
  },
  {
    id: 'copper-scrap',
    name: 'Copper Scrap',
    tag: 'High Value',
    description: 'Heavy berry copper, stripped copper busbars, armature wire, transformer winding copper, pipe scrap.',
    icon: 'Zap',
    typicalSources: 'Electrical panel manufacturers, motor rewinders, transformer makers',
  },
  {
    id: 'brass-scrap',
    name: 'Brass Scrap',
    tag: 'Non-Ferrous',
    description: 'Honey brass, sanitary fittings, turning honey, electrical pins, forged brass components, heat exchanger tubes.',
    icon: 'Sparkles',
    typicalSources: 'Sanitary component makers, brass turning units, valve makers',
  },
  {
    id: 'machinery-scrap',
    name: 'Machinery Scrap',
    tag: 'Heavy Industrial',
    description: 'Decommissioned production lines, CNC machines, mechanical power presses, boiler units, conveyor systems.',
    icon: 'Cpu',
    typicalSources: 'Plant overhauls, factory relocations, obsolete industrial machinery',
  },
  {
    id: 'automobile-scrap',
    name: 'Automobile Scrap',
    tag: 'Auto Ancillary',
    description: 'Automobile stamping skeletons, rejected chassis frames, transmission gears, shock absorber scrap, axles.',
    icon: 'Car',
    typicalSources: 'Tier 1 & Tier 2 auto component manufacturers in Manesar & Bawal',
  },
  {
    id: 'electrical-scrap',
    name: 'Electrical Scrap',
    tag: 'Utility',
    description: 'High voltage electrical switchgear, obsolete control panels, armored cables, sub-station transformers.',
    icon: 'Radio',
    typicalSources: 'Industrial plants, commercial complexes, electrical contractors',
  },
  {
    id: 'factory-scrap',
    name: 'Factory Scrap',
    tag: 'Manufacturing',
    description: 'Production reject parts, stamping skeletons, end-of-run metal stock, tool room scrap, mixed plant waste.',
    icon: 'Factory',
    typicalSources: 'Heavy engineering factories, mass manufacturing units',
  },
  {
    id: 'warehouse-scrap',
    name: 'Warehouse Scrap',
    tag: 'Logistics',
    description: 'Heavy duty pallet racking, slotted angles, steel storage bins, damaged hand pallet trucks, dock levellers.',
    icon: 'Boxes',
    typicalSources: 'Logistics hubs, 3PL warehouses in Bilaspur & Dharuhera',
  },
  {
    id: 'plastic-scrap',
    name: 'Plastic Scrap',
    tag: 'Industrial Polymers',
    description: 'Industrial HD drums, crates, polycarbonate sheets, polypropylene runner scrap, industrial packaging plastic.',
    icon: 'Recycle',
    typicalSources: 'Injection molding plants, packaging units, chemical plants',
  },
  {
    id: 'mixed-scrap',
    name: 'Mixed & Metal Scrap',
    tag: 'Bulk Lot',
    description: 'All grades of combined industrial lot scrap, plant clearance scrap, yard liquidation materials.',
    icon: 'Scale',
    typicalSources: 'Site demolitions, unit liquidation, comprehensive yard cleanups',
  },
];

export const TARGET_INDUSTRIES = [
  { name: 'Manufacturing Companies', desc: 'Regular production scrap pickup with container bin placement' },
  { name: 'Factories & Industrial Plants', desc: 'Heavy lot clearance with crane mobilization & weighbridge slips' },
  { name: 'Automobile & Ancillary Units', desc: 'Press punchings, sheet skeleton & metal off-cut scrap management' },
  { name: 'Engineering & Tooling Units', desc: 'Machine turnings, tool steel, cast iron beds, precision rejects' },
  { name: 'Warehouses & Logistics Parks', desc: 'Racking dismantle, pallet scrap & logistics facility cleanups' },
  { name: 'Construction & Project Sites', desc: 'Structural TMT scrap, rebar ends, scaffolding pipes & girders' },
  { name: 'Workshops & Fabrication Units', desc: 'Welding cut-offs, plate remnants, angle channels & pipes' },
  { name: 'Commercial & Corporate Units', desc: 'HVAC dismantling, chiller scrap, generator & electrical panels' },
];

export const STATUS_OPTIONS = [
  { value: 'NEW', label: 'New Enquiry', color: '#38BDF8', bg: 'rgba(56, 189, 248, 0.15)' },
  { value: 'UNDER_REVIEW', label: 'Under Review', color: '#FBBF24', bg: 'rgba(251, 191, 36, 0.15)' },
  { value: 'CONTACTED', label: 'Contacted', color: '#A78BFA', bg: 'rgba(167, 139, 250, 0.15)' },
  { value: 'QUOTATION_GIVEN', label: 'Quotation Given', color: '#FB923C', bg: 'rgba(251, 146, 60, 0.15)' },
  { value: 'PICKUP_SCHEDULED', label: 'Pickup Scheduled', color: '#34D399', bg: 'rgba(52, 211, 153, 0.15)' },
  { value: 'COMPLETED', label: 'Completed', color: '#10B981', bg: 'rgba(16, 185, 129, 0.2)' },
  { value: 'CANCELLED', label: 'Cancelled', color: '#F87171', bg: 'rgba(248, 113, 113, 0.15)' },
];
